#define ID_WINDOW                      256
#define PB_TEST                        257
#define RB_VOLUME                      258
#define GB_SCHEMES                     259
#define PB_APPLY                       260
#define LB_ACTIONS                     261
#define LB_SCHEMES                     262
#define EF_SOUND                       263
#define PB_DELETE                      264
#define CSL_VOLUME                     265
#define PB_PLAY                        266
#define PB_HELP                        267
#define ST_SCHEMES                     268
#define ST_ACTIONS                     269
#define ST_SOUND                       270
#define PB_ADD                         271
#define PB_LOCATE                      272
#define PB_COPY                        273
#define PB_RENAME                      274
#define PB_UNDO                        275
#define GB_ACTIONS                     276
