int main(int argc, char *argv[]);
MRESULT EXPENTRY SettingsProc(HWND, ULONG, MPARAM, MPARAM);
MRESULT EXPENTRY ProdInfoProc(HWND, ULONG, MPARAM, MPARAM);
MRESULT EXPENTRY TestProc(HWND, ULONG, MPARAM, MPARAM);
MRESULT EXPENTRY WinProc(HWND, ULONG, MPARAM, MPARAM);
MRESULT EXPENTRY DlgProc(HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2);
MRESULT EXPENTRY FindProc(HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2);

